; tpost1.g
; called after tool 1 has been selected
;
; generated by RepRapFirmware Configuration Tool on Tue Jun 26 2018 13:03:45 GMT-0400 (EDT)
; Wait for set temperatures to be reached

M291 P"Waiting for Tool 1 to heat" R"Tool Change" S0  T2
M116 P1

M291 P"Tool change complete" R"Tool Change" S0  T2