; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.2.2 on Sun Feb 14 2021 19:44:49 GMT-0500 (Eastern Standard Time)
M280 P0 S90 ; retract BLTouch
